### ISSUE TITLE
CORREGIR QUE LAS PESTAÑAS DE TRASPARENCIA SOLO SE ACTIVAN AL HACER CLIC

### ISSUE THREAD

**Issue by edymac** [MASTERPC-CIA/gadparaisocelen#1]
EL CLIENTE MENCIONA QUE NO SE LISTAN O MUESTRAN LO QUE SE SUBE , SOLO SE MUESTR AL HACER CLIC

**Comment by mariuxikndo** [comment]
Configurada la opción para que se visualicen los nuevos items de menú que agrega el usuario al menú principal.
